name: Terraform Pipeline

on:
  push:
    branches:
      - main   # alterei para main, branch principal do deploy

env:
  TERRAFORM_VERSION: 1.13.1

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Step 01 - Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Step 02 - Checkout Repository
      uses: actions/checkout@v4

    - name: Step 03 - Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Step 04 - Terraform Init
      run: terraform -chdir=./terraform init

    - name: Step 05 - Terraform Validate
      run: terraform -chdir=./terraform validate

    - name: Step 06 - Terraform Format Check
      run: terraform -chdir=./terraform fmt -check -diff -recursive

    - name: Step 07 - Terraform Plan
      run: terraform -chdir=./terraform plan -out=tfplan

    - name: Step 08 - Checkov Security Scan
      uses: bridgecrewio/checkov-action@master
      with:
        framework: terraform
        output_format: cli
        output_file_path: console
        soft_fail: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Step 01 - Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Step 02 - Checkout Repository
      uses: actions/checkout@v4

    - name: Step 03 - Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Step 04 - Terraform Init
      run: terraform -chdir=./terraform init

    - name: Step 05 - Terraform Plan
      run: terraform -chdir=./terraform plan -out=tfplan

    - name: Step 06 - Terraform Apply
      run: terraform -chdir=./terraform apply -auto-approve tfplan

    - name: Step 07 - Terraform Show
      run: terraform -chdir=./terraform show
